# Generated by Django 4.2.20 on 2025-09-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='source_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Код подразделения 1С'),
        ),
        migrations.AddField(
            model_name='jobtitle',
            name='source_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Код подразделения 1С'),
        ),
    ]
