# Generated by Django 4.2.20 on 2025-09-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_department_source_id_jobtitle_source_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtitle',
            name='source_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Код должности 1С'),
        ),
    ]
