# Generated by Django 4.2.20 on 2025-12-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_alter_jobtitle_source_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='source_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ГУИД 1С'),
        ),
        migrations.AlterField(
            model_name='jobtitle',
            name='source_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ГУИД 1С'),
        ),
    ]
