# Generated by Django 4.2.3 on 2024-04-01 14:20

import app.bot.models.testing_module
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SetsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='title')),
                ('tag', models.CharField(blank=True, max_length=50, null=True, verbose_name='tag')),
            ],
            options={
                'verbose_name': 'settings',
                'verbose_name_plural': 'settings',
                'db_table': 'settings',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SetsListParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='title')),
                ('tag', models.CharField(blank=True, max_length=50, null=True, verbose_name='tag')),
                ('value', models.CharField(blank=True, max_length=200, verbose_name='value')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='settings/uploads_photo', verbose_name='photo')),
            ],
            options={
                'verbose_name': 'sets parameter',
                'verbose_name_plural': 'sets parameters',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='internal_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated_at')),
                ('is_actual', models.BooleanField(default=False, verbose_name='is_actual')),
                ('state', models.IntegerField(choices=[(0, 'NOT_ACTIVE'), (1, 'ACTIVE'), (2, 'DELETED')], default=0, null=True, verbose_name='state')),
                ('user_id', models.BigIntegerField(unique=True, verbose_name='user_id')),
                ('user_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='user_name')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='full_name')),
                ('date_of_birth', models.CharField(blank=True, max_length=100, null=True, verbose_name='date_of_birth')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='phone')),
                ('language', models.CharField(blank=True, max_length=20, null=True, verbose_name='language')),
                ('tg_mention', models.CharField(blank=True, max_length=100, null=True, verbose_name='tg_mention')),
                ('testing_process', models.BooleanField(default=False, verbose_name='testing_process')),
                ('rating', models.CharField(choices=[('CHAMPION', 'champion'), ('MASTER', 'master'), ('EXPERT', 'expert'), ('BEGINNER', 'beginner'), ('STUDENT', 'student'), ('RESEARCHER', 'researcher')], default='BEGINNER', max_length=150)),
                ('current_question_index', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'TelegramUser',
                'verbose_name_plural': "TelegramUser's",
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UserTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='internal_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated_at')),
                ('is_actual', models.BooleanField(default=False, verbose_name='is_actual')),
                ('state', models.IntegerField(choices=[(0, 'NOT_ACTIVE'), (1, 'ACTIVE'), (2, 'DELETED')], default=0, null=True, verbose_name='state')),
                ('user_answer', models.JSONField(default=app.bot.models.testing_module.default_user_answer, verbose_name='user answer')),
                ('complete', models.BooleanField(default=False, verbose_name='complete')),
                ('quantity_correct', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('quantity_not_correct', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'UserTest',
                'verbose_name_plural': 'UserTests',
            },
        ),
    ]
