# Generated by Django 4.2.3 on 2024-04-01 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('educational_module', '0001_initial'),
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertest',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='educational_module.topicquestion', verbose_name='question'),
        ),
        migrations.AddField(
            model_name='usertest',
            name='training',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='educational_module.trainingcourse', verbose_name='training'),
        ),
        migrations.AddField(
            model_name='usertest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bot.telegramuser', verbose_name='user'),
        ),
        migrations.AddField(
            model_name='setslistparameter',
            name='sets_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SetsListParameter', to='bot.setslist', verbose_name='settings'),
        ),
    ]
