# Generated by Django 4.2.3 on 2024-10-17 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('educational_module', '0001_initial'),
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertest',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='educational_module.topicquestion', verbose_name='-'),
        ),
        migrations.AddField(
            model_name='usertest',
            name='training',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='educational_module.trainingcourse', verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='usertest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bot.telegramuser', verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='userread',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational_module.trainingcourse', verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='userread',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational_module.coursetopic', verbose_name='Тема курса'),
        ),
        migrations.AddField(
            model_name='userread',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.telegramuser', verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='educational_module.company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='telegramgroup',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='Пользователи', to='bot.telegramuser'),
        ),
        migrations.AddField(
            model_name='setslistparameter',
            name='sets_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SetsListParameter', to='bot.setslist', verbose_name='settings'),
        ),
        migrations.AlterUniqueTogether(
            name='userread',
            unique_together={('user', 'course', 'topic')},
        ),
    ]
