# Generated by Django 4.2.3 on 2024-04-25 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_useraction'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name Group')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('users', models.ManyToManyField(blank=True, related_name='groups', to='bot.telegramuser')),
            ],
            options={
                'verbose_name': 'TelegramGroup',
                'verbose_name_plural': 'TelegramGroups',
                'ordering': ['name'],
            },
        ),
    ]
