# Generated by Django 4.2.3 on 2024-05-29 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_telegramgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='rating',
        ),
    ]
