# Generated by Django 4.2.3 on 2024-06-06 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educational_module', '0008_company'),
        ('bot', '0006_telegramuser_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational_module.trainingcourse', verbose_name='Course')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational_module.coursetopic', verbose_name='Topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.telegramuser', verbose_name='User')),
            ],
            options={
                'unique_together': {('user', 'course', 'topic')},
            },
        ),
    ]
