# Generated by Django 4.2.3 on 2024-08-06 10:00

import app.bot.models.testing_module
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educational_module', '0011_company_image_test_failed_company_image_test_passed'),
        ('bot', '0007_userread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramgroup',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='telegramgroup',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование группы'),
        ),
        migrations.AlterField(
            model_name='telegramgroup',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='Пользователи', to='bot.telegramuser'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='educational_module.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='language',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='user_id',
            field=models.BigIntegerField(unique=True, verbose_name='Telegram ID пользователя'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram имя пользователя '),
        ),
        migrations.AlterField(
            model_name='useraction',
            name='action_text',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Action Text'),
        ),
        migrations.AlterField(
            model_name='userread',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational_module.trainingcourse', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='userread',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational_module.coursetopic', verbose_name='Тема курса'),
        ),
        migrations.AlterField(
            model_name='userread',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.telegramuser', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='usertest',
            name='complete',
            field=models.BooleanField(default=False, verbose_name='Успешно'),
        ),
        migrations.AlterField(
            model_name='usertest',
            name='quantity_correct',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Процент правильных ответов'),
        ),
        migrations.AlterField(
            model_name='usertest',
            name='quantity_not_correct',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Процент не правильных ответов'),
        ),
        migrations.AlterField(
            model_name='usertest',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='educational_module.topicquestion', verbose_name='-'),
        ),
        migrations.AlterField(
            model_name='usertest',
            name='training',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='educational_module.trainingcourse', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='usertest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bot.telegramuser', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='usertest',
            name='user_answer',
            field=models.JSONField(default=app.bot.models.testing_module.default_user_answer, verbose_name='Ответы пользователя'),
        ),
    ]
