# Generated by Django 4.2.20 on 2025-09-10 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_alter_telegramgroup_options_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Username')),
                ('chat_id', models.BigIntegerField(blank=True, null=True, verbose_name='Chat ID')),
                ('update_id', models.BigIntegerField(blank=True, null=True, verbose_name='Update ID')),
                ('event_type', models.CharField(choices=[('message', 'Сообщение'), ('callback', 'Кнопка (callback)'), ('command', 'Команда'), ('error', 'Ошибка'), ('system', 'Система')], db_index=True, max_length=20, verbose_name='Тип события')),
                ('action_key', models.CharField(db_index=True, max_length=64, verbose_name='Действие')),
                ('content_text', models.TextField(blank=True, null=True, verbose_name='Текст/контент')),
                ('data', models.JSONField(blank=True, null=True, verbose_name='Детали')),
                ('handler', models.CharField(blank=True, max_length=200, null=True, verbose_name='Хендлер')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='FSM стейт')),
                ('is_private', models.BooleanField(default=True, verbose_name='Личный чат')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_logs', to='bot.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Событие бота',
                'verbose_name_plural': 'События бота',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['telegram_id', 'created_at'], name='core_boteve_telegra_a02ee4_idx'), models.Index(fields=['event_type', 'action_key'], name='core_boteve_event_t_49da59_idx')],
            },
        ),
    ]
