# Generated by Django 4.2.20 on 2025-04-23 15:25

import django_ckeditor_5.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('is_actual', models.BooleanField(default=True, verbose_name='Is actual')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company', verbose_name='Логотип компании')),
                ('certificate_template', models.FileField(blank=True, null=True, upload_to='company/certificate', verbose_name='Шаблон сертификата')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('is_actual', models.BooleanField(default=True, verbose_name='Is actual')),
                ('name', models.CharField(max_length=100, verbose_name='Должность')),
                ('source_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ГУИД 1С')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SettingsBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('is_actual', models.BooleanField(default=True, verbose_name='Is actual')),
                ('image_start', models.ImageField(blank=True, null=True, upload_to='company/start_images', verbose_name='Стартовое изображение для ТГ')),
                ('image_list_courses', models.ImageField(blank=True, null=True, upload_to='company/list_courses', verbose_name='Изображение для списка курсов в ТГ')),
                ('image_settings', models.ImageField(blank=True, null=True, upload_to='company/list_settings', verbose_name='Изображение для настроек в ТГ')),
                ('image_progress', models.ImageField(blank=True, null=True, upload_to='company/image_progress', verbose_name='Изображение для прогресса в ТГ')),
                ('image_test_passed', models.ImageField(blank=True, null=True, upload_to='company/test_passed', verbose_name='Изображение для успешно пройденного теста')),
                ('image_test_failed', models.ImageField(blank=True, null=True, upload_to='company/test_failed', verbose_name='Изображение для неудачно пройденного теста')),
                ('image_test_start', models.ImageField(blank=True, null=True, upload_to='company/start_images', verbose_name='Стартовое изображение для теста')),
                ('bot_help_text', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание бота для справки')),
                ('bot_version', models.CharField(blank=True, max_length=20, null=True, verbose_name='Версия бота')),
                ('image_help', models.ImageField(blank=True, null=True, upload_to='company/help', verbose_name='Изображение для справки о боте')),
                ('image_progress_good', models.ImageField(blank=True, null=True, upload_to='company/progress', verbose_name='Позитивное изображение для прогресса')),
                ('image_progress_bad', models.ImageField(blank=True, null=True, upload_to='company/progress', verbose_name='Негативное изображение для прогресса')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Настройки бота',
                'verbose_name_plural': 'Настройки ботов',
                'ordering': ['company'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('is_actual', models.BooleanField(default=True, verbose_name='Is actual')),
                ('name', models.CharField(max_length=100, verbose_name='Подразделение')),
                ('source_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ГУИД 1С')),
                ('job_titles', models.ManyToManyField(blank=True, related_name='departments', to='organization.jobtitle', verbose_name='Должности')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='organization.department', verbose_name='Родительское подразделение')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
                'ordering': ['name'],
            },
        ),
    ]
