# Generated by Django 4.2.20 on 2025-04-24 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='organization.company', verbose_name='Компания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='job_titles',
            field=models.ManyToManyField(blank=True, related_name='departments_of_job_title', to='organization.jobtitle', verbose_name='Должности'),
        ),
    ]
