# Generated by Django 4.2.20 on 2025-05-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_department_company_alter_department_job_titles'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsbot',
            name='url_web_app',
            field=models.URLField(blank=True, null=True, verbose_name='URL для WebApp'),
        ),
    ]
