# Generated by Django 4.2.20 on 2025-07-25 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='is_actual',
            field=models.BooleanField(default=True, verbose_name='Актуальное'),
        ),
        migrations.AlterField(
            model_name='department',
            name='is_actual',
            field=models.BooleanField(default=True, verbose_name='Актуальное'),
        ),
        migrations.AlterField(
            model_name='jobtitle',
            name='is_actual',
            field=models.BooleanField(default=True, verbose_name='Актуальное'),
        ),
        migrations.AlterField(
            model_name='settingsbot',
            name='is_actual',
            field=models.BooleanField(default=True, verbose_name='Актуальное'),
        ),
    ]
