# Generated by Django 4.2.20 on 2025-11-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_company_is_actual_alter_department_is_actual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsbot',
            name='admin_contact_message',
            field=models.TextField(blank=True, null=True, verbose_name='Контакт администратора для связи'),
        ),
    ]
