# Generated by Django 4.2.3 on 2024-04-22 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='exchange_date')),
            ],
            options={
                'verbose_name': 'ExchangeLog',
                'verbose_name_plural': 'ExchangeLogs',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='internal_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated_at')),
                ('is_actual', models.BooleanField(default=False, verbose_name='is_actual')),
                ('url', models.CharField(blank=True, max_length=600, null=True)),
                ('text', models.TextField(null=True)),
                ('response', models.TextField(null=True)),
                ('log_type', models.CharField(choices=[('OUTPUT', 'Output'), ('INPUT', 'Input')], max_length=50)),
            ],
            options={
                'verbose_name': 'Request Log',
                'verbose_name_plural': 'Requests Log',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DynamicModel',
            fields=[
                ('internal_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='internal_id')),
                ('instance', models.IntegerField(blank=True, null=True, verbose_name='instance')),
                ('exchange_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='exchange_date')),
                ('id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='external_id')),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('dynamic_data', models.JSONField()),
                ('exchange_log', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.exchangelog', verbose_name='exchange_log')),
            ],
            options={
                'verbose_name': 'DynamicModel',
                'verbose_name_plural': 'DynamicModels',
                'ordering': ['-exchange_date'],
            },
        ),
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='changed')),
                ('model', models.CharField(max_length=255, null=True, verbose_name='model')),
                ('record_id', models.IntegerField(null=True, verbose_name='record_id')),
                ('action_on_model', models.CharField(choices=[('create', 'ACTION_CREATE'), ('update', 'ACTION_UPDATE'), ('delete', 'ACTION_DELETE')], max_length=50, null=True, verbose_name='action')),
                ('data_history', models.JSONField(default=dict, verbose_name='data_history')),
                ('data', models.JSONField(default=dict, verbose_name='data')),
                ('ipaddress', models.CharField(max_length=15, null=True, verbose_name='ipaddress')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Change log',
                'verbose_name_plural': 'Changes log',
                'ordering': ('-changed',),
            },
        ),
    ]
