# Generated by Django 4.2.20 on 2026-01-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Настройка напоминаний', max_length=200, verbose_name='Наименование настройки')),
                ('enable_gif', models.BooleanField(default=False, help_text='Если включено и загружен GIF, отправлять анимацию перед текстом', verbose_name='Отправлять GIF перед сообщением')),
                ('gif', models.FileField(blank=True, null=True, upload_to='gif_reminder/', verbose_name='Общий GIF для напоминаний')),
                ('enable_scheduler', models.BooleanField(default=True, verbose_name='Включить планировщик напоминаний')),
                ('schedule_start_hour', models.PositiveSmallIntegerField(default=10, help_text='Час в 24-часовом формате (0-23), от которого строятся слоты', verbose_name='Час запуска')),
                ('schedule_interval_hours', models.FloatField(default=24.0, help_text='Шаг между слотами в часах; ≤0 трактуется как 24', verbose_name='Интервал повтора (часы)')),
                ('poll_interval_minutes', models.PositiveSmallIntegerField(default=5, help_text='Как часто поллер проверяет, пора ли запускать рассылку', verbose_name='Период опроса (мин)')),
                ('monday', models.BooleanField(default=True, verbose_name='Понедельник')),
                ('tuesday', models.BooleanField(default=True, verbose_name='Вторник')),
                ('wednesday', models.BooleanField(default=True, verbose_name='Среда')),
                ('thursday', models.BooleanField(default=True, verbose_name='Четверг')),
                ('friday', models.BooleanField(default=True, verbose_name='Пятница')),
                ('saturday', models.BooleanField(default=True, verbose_name='Суббота')),
                ('sunday', models.BooleanField(default=True, verbose_name='Воскресенье')),
                ('batch_size', models.PositiveSmallIntegerField(default=25, help_text='Количество пользователей в одном пакете', verbose_name='Размер пакета')),
                ('delay_between_users', models.FloatField(default=0.15, help_text='Пауза между отправками в рамках пакета', verbose_name='Задержка между пользователями (сек)')),
                ('delay_between_batches', models.PositiveSmallIntegerField(default=3, help_text='Пауза между обработкой батчей', verbose_name='Задержка между пакетами (сек)')),
                ('max_retry_attempts', models.PositiveSmallIntegerField(default=5, help_text='Сколько раз повторять отправку после ошибок', verbose_name='Макс. число попыток')),
                ('cleanup_age_days', models.PositiveSmallIntegerField(default=30, help_text='Старше скольких дней удалять записи SchedulerLog', verbose_name='Дни до очистки логов')),
            ],
            options={
                'verbose_name': 'Настройки напоминаний',
                'verbose_name_plural': 'Настройки напоминаний',
            },
        ),
        migrations.CreateModel(
            name='SchedulerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100, verbose_name='Название задачи')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('running', 'Выполняется'), ('completed', 'Завершено успешно'), ('failed', 'Ошибка выполнения')], default='pending', max_length=20, verbose_name='Статус')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Время начала')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Время завершения')),
                ('execution_time', models.FloatField(blank=True, null=True, verbose_name='Время выполнения (сек)')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Сообщение об ошибке')),
                ('total_messages_sent', models.PositiveIntegerField(default=0, verbose_name='Всего отправлено сообщений')),
                ('total_errors', models.PositiveIntegerField(default=0, verbose_name='Количество ошибок')),
                ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Дополнительная информация')),
            ],
            options={
                'verbose_name': 'Лог планировщика',
                'verbose_name_plural': 'Логи планировщика',
                'ordering': ['-start_time'],
            },
        ),
    ]
