# Generated by Django 4.2.3 on 2024-10-08 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot', '0010_alter_telegramuser_is_actual_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название должности')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание должности')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Lightning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Молния')),
                ('description_of_consequences', models.TextField(blank=True, null=True, verbose_name='Описание последствий')),
                ('incident_location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Место происшествия')),
                ('incident_coordinates', models.CharField(blank=True, max_length=100, null=True, verbose_name='Координаты происшествия')),
                ('plan_of_action', models.TextField(blank=True, null=True, verbose_name='План мероприятий по ликвидации происшествия')),
                ('responsible_persons', models.TextField(blank=True, null=True, verbose_name='Ответственные')),
                ('group', models.ManyToManyField(blank=True, to='bot.telegramgroup', verbose_name='Группа пользователей')),
                ('job_titles', models.ManyToManyField(blank=True, to='lightning.jobtitle', verbose_name='Должности')),
                ('user', models.ManyToManyField(blank=True, to='bot.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Молния',
                'verbose_name_plural': 'Молнии',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='LightningMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Сообщение')),
                ('button_text', models.CharField(default='Далее', max_length=25, verbose_name='Текст для кнопки')),
                ('image_lightning', models.ImageField(blank=True, null=True, upload_to='image_lightning/', verbose_name='Изображение')),
                ('file_lightning', models.FileField(blank=True, null=True, upload_to='file_lightning', verbose_name='Файл для сообщения')),
                ('send_text', models.BooleanField(default=False, verbose_name='Отправлять текст')),
                ('send_file', models.BooleanField(default=False, verbose_name='Отправлять файл')),
                ('lightning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='lightning.lightning', verbose_name='Молния')),
            ],
        ),
    ]
