# Generated by Django 4.2.3 on 2024-10-08 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lightning', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lightningmessage',
            options={'ordering': ['lightning__title'], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.CreateModel(
            name='LightningQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Вопрос')),
                ('is_multiple_choice', models.BooleanField(default=False, verbose_name='Несколько ответов')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('min_test_percent_course', models.IntegerField(default=90, verbose_name='Минимальный процент для прохождения теста')),
                ('is_display_question', models.BooleanField(default=False, verbose_name='Отобразить')),
                ('lightning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='lightning.lightning', verbose_name='Молния')),
            ],
            options={
                'verbose_name': 'Вопрос молнии',
                'verbose_name_plural': 'Вопросы молнии',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LightningAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=5, null=True, verbose_name='Номер')),
                ('text', models.TextField(verbose_name='Текст ответа')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный ответ')),
                ('is_display_answer', models.BooleanField(default=False, verbose_name='Отобразить')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='lightning.lightningquestion', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вариант ответа молнии',
                'verbose_name_plural': 'Варианты ответов молнии',
                'ordering': ['number'],
            },
        ),
    ]
