# Generated by Django 4.2.3 on 2024-10-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightning', '0002_alter_lightningmessage_options_lightningquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightning',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата'),
        ),
    ]
