# Generated by Django 4.2.3 on 2024-10-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightning', '0003_lightning_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lightningmessage',
            name='content',
            field=models.TextField(max_length=2000, verbose_name='Сообщение'),
        ),
    ]
