# Generated by Django 4.2.3 on 2024-10-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightning', '0004_alter_lightningmessage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightningmessage',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
