# Generated by Django 4.2.3 on 2024-10-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightning', '0005_lightningmessage_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightning',
            name='min_test_percent_course',
            field=models.IntegerField(default=90, verbose_name='Минимальный процент для прохождения теста'),
        ),
        migrations.AlterField(
            model_name='lightningmessage',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Порядок'),
        ),
    ]
