# Generated by Django 4.2.3 on 2024-10-20 23:15

import app.lightning.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_telegramgroup_lightning_group'),
        ('lightning', '0007_remove_lightningquestion_min_test_percent_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightningTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата записи теста')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновление записи теста')),
                ('user_answer', models.JSONField(default=app.lightning.models.default_user_answer, verbose_name='Ответы пользователя')),
                ('complete', models.BooleanField(default=False, verbose_name='Успешно')),
                ('quantity_correct', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Процент правильных ответов')),
                ('quantity_not_correct', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Процент не правильных ответов')),
                ('lightning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lightning.lightning', verbose_name='Молния')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lightning.lightningquestion', verbose_name='Вопрос')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Результат тестирования',
                'verbose_name_plural': 'Результаты тестирования',
                'ordering': ['created_at'],
                'unique_together': {('user', 'lightning')},
            },
        ),
        migrations.CreateModel(
            name='LightningRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Прочитано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_read', models.BooleanField(default=False)),
                ('lightning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lightning.lightning', verbose_name='Молния')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Статус чтения молнии',
                'verbose_name_plural': 'Статусы чтения молний',
                'ordering': ['created_at'],
                'unique_together': {('user', 'lightning')},
            },
        ),
    ]
