# Generated by Django 4.2.20 on 2025-04-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('is_actual', models.BooleanField(default=True, verbose_name='Is actual')),
                ('regbot_active', models.BooleanField(default=False, verbose_name='Включить бот регистрации')),
                ('regbot_api_url', models.URLField(verbose_name='URL API для регистрации')),
                ('regbot_telegram_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на бота регистрации')),
                ('api_key', models.CharField(blank=True, max_length=100, null=True, verbose_name='API ключ')),
                ('send_welcome_message', models.BooleanField(default=True, verbose_name='Отправлять приветственное сообщение')),
                ('welcome_message_text', models.TextField(blank=True, null=True, verbose_name='Текст приветственного сообщения')),
            ],
            options={
                'verbose_name': 'Настройки регистрации',
                'verbose_name_plural': 'Настройки регистрации',
            },
        ),
    ]
