# Generated by Django 4.2.9 on 2024-01-25 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(unique=True, verbose_name='user_id')),
                ('user_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='user_name')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='full_name')),
                ('date_of_birth', models.CharField(blank=True, max_length=100, null=True, verbose_name='date_of_birth')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='phone')),
                ('language', models.CharField(blank=True, max_length=20, null=True, verbose_name='language')),
                ('tg_mention', models.CharField(blank=True, max_length=100, null=True, verbose_name='tg_mention')),
                ('testing_process', models.BooleanField(default=False, verbose_name='testing_process')),
                ('rating', models.CharField(choices=[('CHAMPION', 'champion'), ('MASTER', 'master'), ('EXPERT', 'expert'), ('BEGINNER', 'beginner'), ('STUDENT', 'student'), ('RESEARCHER', 'researcher')], default='BEGINNER', max_length=150)),
            ],
            options={
                'verbose_name': 'TelegramUser',
                'verbose_name_plural': "TelegramUser's",
                'ordering': ['id'],
            },
        ),
    ]
