# Generated by Django 4.2.20 on 2025-08-20 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100, verbose_name='Название задачи')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('running', 'Выполняется'), ('completed', 'Завершено успешно'), ('failed', 'Ошибка выполнения')], default='pending', max_length=20, verbose_name='Статус')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Время начала')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Время завершения')),
                ('execution_time', models.FloatField(blank=True, null=True, verbose_name='Время выполнения (сек)')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Сообщение об ошибке')),
                ('total_messages_sent', models.PositiveIntegerField(default=0, verbose_name='Всего отправлено сообщений')),
                ('total_errors', models.PositiveIntegerField(default=0, verbose_name='Количество ошибок')),
                ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Дополнительная информация')),
            ],
            options={
                'verbose_name': 'Лог планировщика',
                'verbose_name_plural': 'Логи планировщика',
                'ordering': ['-start_time'],
            },
        ),
    ]
