# Generated by Django 4.2.20 on 2025-04-24 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertest',
            name='state',
        ),
    ]
