# Generated by Django 4.2.3 on 2024-06-03 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educational_module', '0008_company'),
        ('bot', '0005_remove_telegramuser_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='educational_module.company', verbose_name='Company'),
        ),
    ]
