# Generated by Django 4.2.3 on 2024-09-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_telegramuser_first_name_telegramuser_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='is_actual',
            field=models.BooleanField(default=False, verbose_name='Актуальный'),
        ),
        migrations.AlterField(
            model_name='usertest',
            name='is_actual',
            field=models.BooleanField(default=False, verbose_name='Актуальный'),
        ),
    ]
