# Generated by Django 4.2.3 on 2024-10-08 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_alter_telegramuser_is_actual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='job_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lightning.jobtitle', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='is_actual',
            field=models.BooleanField(default=False, verbose_name='Отобразить'),
        ),
        migrations.AlterField(
            model_name='usertest',
            name='is_actual',
            field=models.BooleanField(default=False, verbose_name='Отобразить'),
        ),
    ]
