# Generated by Django 4.2.3 on 2024-11-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_telegramuser_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='country',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='email',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Email'),
        ),
    ]
