# Generated by Django 4.2.3 on 2024-11-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0014_telegramuser_country_telegramuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='image_telegramuser',
            field=models.ImageField(blank=True, null=True, upload_to='telegramuser', verbose_name='Фото пользователя'),
        ),
    ]
