# Generated by Django 4.2.3 on 2024-12-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_telegramuser_image_telegramuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramgroup',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='groups', to='bot.telegramuser', verbose_name='Пользователи'),
        ),
    ]
