# Generated by Django 4.2.3 on 2024-12-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_alter_telegramgroup_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
    ]
