# Generated by Django 4.2.3 on 2025-03-19 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0017_alter_telegramuser_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramgroup',
            name='lightning_group',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='department',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='job_title',
        ),
    ]
