# Generated by Django 4.2.3 on 2025-03-20 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0003_alter_department_jobtitle'),
        ('bot', '0018_remove_telegramgroup_lightning_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference_data.department', verbose_name='Подразделение'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='job_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference_data.jobtitle', verbose_name='Должность'),
        ),
    ]
