# Generated by Django 4.2.3 on 2024-09-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlog',
            name='is_actual',
            field=models.BooleanField(default=False, verbose_name='Актуальный'),
        ),
    ]
