# Generated by Django 4.2.3 on 2024-05-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_telegramgroup'),
        ('educational_module', '0002_trainingcourse_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcourse',
            name='image_course',
            field=models.ImageField(blank=True, null=True, upload_to='training_course', verbose_name='image course'),
        ),
        migrations.AlterField(
            model_name='trainingcourse',
            name='group',
            field=models.ManyToManyField(blank=True, null=True, to='bot.telegramgroup', verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='trainingcourse',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, to='bot.telegramuser', verbose_name='пользователь'),
        ),
    ]
