# Generated by Django 4.2.3 on 2024-05-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_module', '0003_trainingcourse_image_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetopic',
            name='image_course_topic',
            field=models.ImageField(blank=True, null=True, upload_to='Course_Topic', verbose_name='image course topic'),
        ),
    ]
