# Generated by Django 4.2.3 on 2024-05-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_module', '0004_coursetopic_image_course_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetopic',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='Course_Topic', verbose_name='pdf_file'),
        ),
    ]
