# Generated by Django 4.2.3 on 2024-05-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_module', '0005_coursetopic_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetopic',
            name='min_test_percent_topic',
            field=models.IntegerField(default=90, verbose_name='minimum test percent topic'),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='min_test_percent_course',
            field=models.IntegerField(default=90, verbose_name='minimum test percent course'),
        ),
    ]
