# Generated by Django 4.2.3 on 2024-06-03 13:12

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_module', '0007_alter_topicquestion_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('logo_company', models.ImageField(blank=True, null=True, upload_to='company', verbose_name='logo company')),
                ('color_theme_company', colorfield.fields.ColorField(default='#4a8bed', image_field=None, max_length=25, samples=None, verbose_name='color theme company')),
                ('image_start_company', models.ImageField(blank=True, null=True, upload_to='start_images', verbose_name='image start company')),
                ('image_list_courses', models.ImageField(blank=True, null=True, upload_to='list_courses', verbose_name='image list courses')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
    ]
