# Generated by Django 4.2.3 on 2024-06-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_module', '0010_company_image_list_settings_company_image_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='image_test_failed',
            field=models.ImageField(blank=True, null=True, upload_to='test failed', verbose_name='image test failed'),
        ),
        migrations.AddField(
            model_name='company',
            name='image_test_passed',
            field=models.ImageField(blank=True, null=True, upload_to='test passed', verbose_name='image test passed'),
        ),
    ]
