# Generated by Django 4.2.3 on 2024-09-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_module', '0013_alter_company_spravka_for_bot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetopic',
            name='title',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Заголовок'),
        ),
    ]
