# Generated by Django 4.2.3 on 2024-09-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_module', '0021_coursedirection_trainingcourse_course_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcourse',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Автор'),
        ),
    ]
