# Generated by Django 4.2.3 on 2024-10-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_module', '0023_trainingcourse_archive_alter_answeroption_is_actual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answeroption',
            name='is_actual',
            field=models.BooleanField(default=False, verbose_name='Отобразить'),
        ),
        migrations.AlterField(
            model_name='coursetopic',
            name='is_actual',
            field=models.BooleanField(default=False, verbose_name='Отобразить'),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='is_actual',
            field=models.BooleanField(default=False, verbose_name='Отобразить'),
        ),
        migrations.AlterField(
            model_name='topicquestion',
            name='is_actual',
            field=models.BooleanField(default=False, verbose_name='Отобразить'),
        ),
        migrations.AlterField(
            model_name='trainingcourse',
            name='is_actual',
            field=models.BooleanField(default=False, verbose_name='Отобразить'),
        ),
    ]
