# Generated by Django 4.2.3 on 2024-11-14 08:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_module', '0024_alter_answeroption_is_actual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='image_progess_bad',
            field=models.ImageField(blank=True, null=True, upload_to='test_failed', verbose_name='Негативное изображение для прогресса'),
        ),
        migrations.AlterField(
            model_name='company',
            name='image_progess_good',
            field=models.ImageField(blank=True, null=True, upload_to='test_passed', verbose_name='Позитивное изображение для прогресса'),
        ),
        migrations.AlterField(
            model_name='company',
            name='image_test_failed',
            field=models.ImageField(blank=True, null=True, upload_to='test_failed', verbose_name='Изображение для неудачно пройденного теста'),
        ),
        migrations.AlterField(
            model_name='company',
            name='image_test_passed',
            field=models.ImageField(blank=True, null=True, upload_to='test_passed', verbose_name='Изображение для успешно пройденного теста'),
        ),
        migrations.AlterField(
            model_name='company',
            name='spravka_for_bot',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание бота для справки'),
        ),
    ]
