# Generated by Django 4.2.3 on 2024-12-04 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_module', '0025_alter_company_image_progess_bad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopic',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='заголовок'),
        ),
        migrations.AlterField(
            model_name='topicquestion',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='заголовок'),
        ),
    ]
