# Generated by Django 4.2.3 on 2025-02-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_module', '0026_alter_subtopic_title_alter_topicquestion_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetopic',
            name='title',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Заголовок'),
        ),
    ]
