# Generated by Django 4.2.3 on 2025-02-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_module', '0027_alter_coursetopic_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Настройки регистрации')),
                ('regbot_work', models.BooleanField(default=False, verbose_name='Включить RegBot')),
                ('url_regbot', models.URLField(verbose_name='URL для API')),
            ],
            options={
                'verbose_name': 'Настройки регистрации',
            },
        ),
    ]
