# Generated by Django 4.2.3 on 2025-02-28 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educational_module', '0028_registrationsetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationsetting',
            name='name',
        ),
    ]
