# Generated by Django 4.2.3 on 2025-03-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_module', '0029_remove_registrationsetting_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationsetting',
            name='bot_reg_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на бота регистрации'),
        ),
    ]
