# Generated by Django 4.2.3 on 2025-03-05 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educational_module', '0030_registrationsetting_bot_reg_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScormPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scorm_file', models.FileField(upload_to='scorm_packs/', verbose_name='SCORM пакет')),
                ('manifest_data', models.JSONField(blank=True, null=True, verbose_name='Манифест для веб')),
                ('training_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scormpack', to='educational_module.trainingcourse', verbose_name='Программа обучения')),
            ],
            options={
                'verbose_name': 'SCORM пакет',
                'verbose_name_plural': 'SCORM пакеты',
            },
        ),
    ]
