# Generated by Django 4.2.3 on 2025-03-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_module', '0031_scormpack'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetopic',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='Course_Topic/audio', verbose_name='Аудио файл для курса'),
        ),
        migrations.AddField(
            model_name='coursetopic',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='Course_Topic/video', verbose_name='Видео файл для курса'),
        ),
        migrations.AlterField(
            model_name='coursetopic',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='Course_Topic/pdf', verbose_name='PDF файл для курса'),
        ),
    ]
