# Generated by Django 4.2.3 on 2025-03-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_module', '0032_coursetopic_audio_file_coursetopic_video_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date_news', models.DateField(verbose_name='Дата старта новости')),
                ('end_date_news', models.DateField(blank=True, null=True, verbose_name='Дата завершения новости')),
                ('text_news', models.TextField(verbose_name='Текст новости')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Дата завершения курса'),
        ),
    ]
