# Generated by Django 4.2.3 on 2025-03-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_module', '0033_newsblock_trainingcourse_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=255, verbose_name='Наименование тега')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='tag',
            field=models.ManyToManyField(blank=True, to='educational_module.tag', verbose_name='Тэги'),
        ),
    ]
