# Generated by Django 4.2.3 on 2025-03-12 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educational_module', '0034_tag_trainingcourse_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='TagCourse',
        ),
    ]
