# Generated by Django 4.2.3 on 2025-03-13 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0017_alter_telegramuser_date_of_birth_and_more'),
        ('educational_module', '0035_rename_tag_tagcourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField(verbose_name='Результат')),
                ('certificate_file', models.FileField(upload_to='certificates/', verbose_name='Адрес файла')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('training_course_certificate', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='certificates', to='educational_module.trainingcourse', verbose_name='Программа обучения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='certificates', to='bot.telegramuser', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
            },
        ),
    ]
