# Generated by Django 4.2.3 on 2025-03-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_module', '0036_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='certificate',
            field=models.FileField(blank=True, upload_to='start_certificate', verbose_name='Сертификат'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_file',
            field=models.FileField(blank=True, upload_to='certificates/', verbose_name='Адрес файла'),
        ),
    ]
