# Generated by Django 4.2.3 on 2025-03-14 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0017_alter_telegramuser_date_of_birth_and_more'),
        ('educational_module', '0037_company_certificate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingTrainingCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, verbose_name='Оценка')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bot.telegramuser', verbose_name='Студент')),
                ('training_course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rating_course', to='educational_module.trainingcourse', verbose_name='Программа обучения')),
            ],
        ),
    ]
