# Generated by Django 4.2.3 on 2025-03-20 14:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educational_module', '0038_ratingtrainingcourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsblock',
            name='text_news',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст новости'),
        ),
    ]
