# Generated by Django 4.2.3 on 2025-03-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_module', '0039_alter_newsblock_text_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsblock',
            name='news_title',
            field=models.CharField(default='Новости', max_length=100, verbose_name='Наименование'),
        ),
    ]
