# Generated by Django 4.2.3 on 2025-03-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_module', '0040_newsblock_news_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetopic',
            name='audio_file_readuser',
            field=models.BooleanField(default=False, verbose_name='Отображать аудио файл в ТГ'),
        ),
        migrations.AddField(
            model_name='coursetopic',
            name='video_file_readuser',
            field=models.BooleanField(default=False, verbose_name='Отображать видео файл в ТГ'),
        ),
    ]
