# Generated by Django 4.2.3 on 2025-03-26 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0019_telegramuser_department_telegramuser_job_title'),
        ('educational_module', '0041_coursetopic_audio_file_readuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline_date', models.DateField(verbose_name='Дата дедлайна')),
                ('deadline_groups', models.ManyToManyField(blank=True, related_name='deadlines', to='bot.telegramgroup', verbose_name='Группы')),
                ('deadline_telegramusers', models.ManyToManyField(blank=True, related_name='deadlines', to='bot.telegramuser', verbose_name='Студенты')),
                ('training_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='educational_module.trainingcourse', verbose_name='Программа обучения')),
            ],
            options={
                'verbose_name': 'Дедлайн',
                'verbose_name_plural': 'Дедлайны',
            },
        ),
    ]
