# Generated by Django 4.2.3 on 2025-03-27 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educational_module', '0042_coursedeadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingcourse',
            name='deadline',
        ),
    ]
