# Generated by Django 4.2.20 on 2025-05-23 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0002_coursetopic_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursedeadline',
            name='notification_sent',
        ),
    ]
