# Generated by Django 4.2.20 on 2025-08-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_telegramuser_last_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='last_activity',
            field=models.DateField(blank=True, null=True, verbose_name='Последняя активность'),
        ),
    ]
