# Generated by Django 4.2.20 on 2025-08-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_telegramuser_last_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='state',
            field=models.IntegerField(choices=[(0, 'Неактивный'), (1, 'Активный'), (2, 'Удалённый'), (3, 'Нужно подтвердить')], default=0, null=True, verbose_name='Статус'),
        ),
    ]
