# Generated by Django 4.2.20 on 2025-08-28 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_telegramuser_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramuser',
            old_name='user_id',
            new_name='telegram_id',
        ),
    ]
