# Generated by Django 4.2.20 on 2025-09-05 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_rename_user_id_telegramuser_telegram_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramgroup',
            options={'ordering': ['name'], 'verbose_name': 'Группа молнии', 'verbose_name_plural': 'Группы молний'},
        ),
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'ordering': ['id'], 'verbose_name': 'Пользователь молнии', 'verbose_name_plural': 'Пользователи молнии'},
        ),
    ]
