# Generated by Django 4.2.20 on 2025-10-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_alter_telegramgroup_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='guid_1c',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Код 1С'),
        ),
    ]
