# Generated by Django 4.2.20 on 2025-07-25 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answeroption',
            name='is_actual',
            field=models.BooleanField(default=True, verbose_name='Актуальное'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='is_actual',
            field=models.BooleanField(default=True, verbose_name='Актуальное'),
        ),
        migrations.AlterField(
            model_name='coursedeadline',
            name='is_actual',
            field=models.BooleanField(default=True, verbose_name='Актуальное'),
        ),
        migrations.AlterField(
            model_name='coursedirection',
            name='is_actual',
            field=models.BooleanField(default=True, verbose_name='Актуальное'),
        ),
        migrations.AlterField(
            model_name='coursetopic',
            name='is_actual',
            field=models.BooleanField(default=True, verbose_name='Актуальное'),
        ),
        migrations.AlterField(
            model_name='newsblock',
            name='is_actual',
            field=models.BooleanField(default=True, verbose_name='Актуальное'),
        ),
        migrations.AlterField(
            model_name='ratingtrainingcourse',
            name='is_actual',
            field=models.BooleanField(default=True, verbose_name='Актуальное'),
        ),
        migrations.AlterField(
            model_name='scormpack',
            name='is_actual',
            field=models.BooleanField(default=True, verbose_name='Актуальное'),
        ),
        migrations.AlterField(
            model_name='tagcourse',
            name='is_actual',
            field=models.BooleanField(default=True, verbose_name='Актуальное'),
        ),
        migrations.AlterField(
            model_name='topicquestion',
            name='is_actual',
            field=models.BooleanField(default=True, verbose_name='Актуальное'),
        ),
        migrations.AlterField(
            model_name='trainingcourse',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_courses', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='trainingcourse',
            name='is_actual',
            field=models.BooleanField(default=True, verbose_name='Актуальное'),
        ),
    ]
