# Generated by Django 4.2.20 on 2025-08-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0002_alter_answeroption_is_actual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcourse',
            name='obligatory',
            field=models.BooleanField(default=False, verbose_name='Обязательный'),
        ),
    ]
