# Generated by Django 4.2.20 on 2025-11-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0003_trainingcourse_obligatory'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsblock',
            name='is_important',
            field=models.BooleanField(default=False, verbose_name='Важное'),
        ),
        migrations.AlterField(
            model_name='newsblock',
            name='start_date_news',
            field=models.DateField(verbose_name='Дата публикации'),
        ),
    ]
