# Generated by Django 4.2.20 on 2025-11-06 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_userrating'),
        ('learning_app', '0004_newsblock_is_important_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsblock',
            name='news_title',
            field=models.CharField(default='Новость', max_length=100, verbose_name='Наименование'),
        ),
        migrations.CreateModel(
            name='UserNewsStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('is_actual', models.BooleanField(default=True, verbose_name='Актуальное')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Закреплено')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_app.newsblock', verbose_name='Новость')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Статус прочтения новости',
                'verbose_name_plural': 'Статусы прочтения новостей',
                'unique_together': {('user', 'news')},
            },
        ),
    ]
