# Generated by Django 4.2.20 on 2025-12-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0005_alter_newsblock_news_title_usernewsstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcourse',
            name='open_course',
            field=models.BooleanField(default=False, verbose_name='Открытый'),
        ),
    ]
