# Generated by Django 4.2.20 on 2025-12-15 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_settingsbot_admin_contact_message'),
        ('learning_app', '0006_trainingcourse_open_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObligatoryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('is_actual', models.BooleanField(default=True, verbose_name='Актуальное')),
                ('department', models.ManyToManyField(blank=True, to='organization.department', verbose_name='Подразделения')),
                ('jobtitle', models.ManyToManyField(blank=True, to='organization.jobtitle', verbose_name='Должности')),
                ('training_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligatory_list', to='learning_app.trainingcourse', verbose_name='Программа обучения')),
            ],
            options={
                'verbose_name': 'Список обязательных курсов',
                'verbose_name_plural': 'Списки обязательных курсов',
            },
        ),
    ]
