# Generated by Django 4.2.20 on 2025-12-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0007_obligatorylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcourse',
            name='notification_sent',
            field=models.BooleanField(default=False, verbose_name='Уведомление отправлено'),
        ),
    ]
