# Generated by Django 4.2.20 on 2025-12-29 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_alter_telegramuser_state_subscriptionuser'),
        ('learning_app', '0008_trainingcourse_notification_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAssignmentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('is_actual', models.BooleanField(default=True, verbose_name='Актуальное')),
                ('notified_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время уведомления')),
                ('training_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_notifications', to='learning_app.trainingcourse', verbose_name='Программа обучения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_assignment_notifications', to='bot.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Уведомление о назначении курса',
                'verbose_name_plural': 'Уведомления о назначении курсов',
                'ordering': ['-notified_at'],
                'indexes': [models.Index(fields=['training_course', 'user'], name='learning_ap_trainin_b4c1e0_idx'), models.Index(fields=['-notified_at'], name='learning_ap_notifie_8b78c4_idx')],
                'unique_together': {('training_course', 'user')},
            },
        ),
    ]
