# Generated by Django 4.2.20 on 2026-01-20 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0009_courseassignmentnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicquestion',
            name='course_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learning_app.coursetopic', verbose_name='Тема курса'),
        ),
    ]
