# Generated by Django 4.2.20 on 2026-01-20 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0010_topicquestion_course_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicquestion',
            name='training',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learning_app.trainingcourse', verbose_name='Программа обучения'),
        ),
    ]
