# Generated by Django 4.2.20 on 2026-07-21 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0011_alter_topicquestion_training'),
    ]

    operations = [
        migrations.AddField(
            model_name='scormpack',
            name='course_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scormpack', to='learning_app.coursetopic', verbose_name='Тема программы обучения'),
        ),
        migrations.AddField(
            model_name='scormpack',
            name='name_index',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Стартовый файл SCORM'),
        ),
    ]
