# Generated by Django 4.2.20 on 2026-08-05 09:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0012_scormpack_course_topic_scormpack_name_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='completed_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата успешного прохождения'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='course_title',
            field=models.CharField(blank=True, default='', max_length=400, verbose_name='Название курса'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='expires_at',
            field=models.DateField(blank=True, null=True, verbose_name='Действителен до'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='recipient_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='ФИО получателя'),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='certificate_validity_days',
            field=models.PositiveIntegerField(blank=True, help_text='Оставьте пустым, если сертификат по курсу не выдаётся.', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Срок действия сертификата, дней'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_file',
            field=models.FileField(blank=True, upload_to='certificates/', verbose_name='Файл сертификата'),
        ),
        migrations.AddConstraint(
            model_name='certificate',
            constraint=models.UniqueConstraint(fields=('user', 'training_course'), name='uniq_certificate_user_course'),
        ),
        migrations.AddConstraint(
            model_name='certificate',
            constraint=models.CheckConstraint(check=models.Q(('result__gte', 0), ('result__lte', 100)), name='certificate_result_between_0_and_100'),
        ),
    ]
