# Generated by Django 4.2.3 on 2025-03-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='source_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ГУИД 1С'),
        ),
        migrations.AlterField(
            model_name='jobtitle',
            name='source_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ГУИД 1С'),
        ),
    ]
