# Generated by Django 4.2.3 on 2025-03-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0002_alter_department_source_id_alter_jobtitle_source_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='jobtitle',
            field=models.ManyToManyField(blank=True, related_name='jobtitle_department', to='reference_data.jobtitle', verbose_name='Должность'),
        ),
    ]
