# Generated by Django 4.2.20 on 2025-12-17 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_settingsbot_admin_contact_message'),
        ('integration', '0002_alter_registrationsetting_is_actual'),
    ]

    operations = [
        migrations.CreateModel(
            name='APISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_url', models.URLField(blank=True, null=True, verbose_name='URL API 1С')),
                ('api_username', models.CharField(blank=True, max_length=100, null=True, verbose_name='API Username')),
                ('api_password', models.CharField(blank=True, max_length=100, null=True, verbose_name='API Password')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Настройки API',
                'verbose_name_plural': 'Настройки API',
                'ordering': ['api_url'],
            },
        ),
    ]
