# Generated by Django 4.2.20 on 2026-02-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0003_apisettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationsetting',
            name='regbot_active',
        ),
        migrations.RemoveField(
            model_name='registrationsetting',
            name='regbot_api_url',
        ),
        migrations.RemoveField(
            model_name='registrationsetting',
            name='regbot_telegram_url',
        ),
        migrations.RemoveField(
            model_name='registrationsetting',
            name='send_welcome_message',
        ),
        migrations.RemoveField(
            model_name='registrationsetting',
            name='welcome_message_text',
        ),
        migrations.AddField(
            model_name='registrationsetting',
            name='employee_check_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL для проверки ФИО и ДР'),
        ),
        migrations.AddField(
            model_name='registrationsetting',
            name='name',
            field=models.CharField(default='Подключение к системе регистрации', max_length=100, verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='registrationsetting',
            name='telegram_check_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL для проверки Telegram ID'),
        ),
        migrations.AlterField(
            model_name='registrationsetting',
            name='api_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='API ключ'),
        ),
    ]
