# Generated by Django 4.2.3 on 2024-04-22 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='internal_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated_at')),
                ('is_actual', models.BooleanField(default=False, verbose_name='is_actual')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('main_text', models.TextField(blank=True, null=True, verbose_name='Основной текст')),
            ],
            options={
                'verbose_name': 'Тема курса',
                'verbose_name_plural': 'Темы курса',
                'ordering': ['training_course', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TrainingCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='internal_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated_at')),
                ('is_actual', models.BooleanField(default=False, verbose_name='is_actual')),
                ('title', models.CharField(blank=True, max_length=400, null=True, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('user', models.ManyToManyField(blank=True, null=True, to='bot.telegramuser')),
            ],
            options={
                'verbose_name': 'Курс самоподготовки',
                'verbose_name_plural': 'Курсы самоподготовки',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TopicQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='internal_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated_at')),
                ('is_actual', models.BooleanField(default=False, verbose_name='is_actual')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='Заголовок')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='topic_questions', to='educational_module.coursetopic', verbose_name='тема')),
                ('training', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='educational_module.trainingcourse', verbose_name='курс')),
            ],
            options={
                'verbose_name': 'Вопрос по теме',
                'verbose_name_plural': 'Вопросы по темам',
                'ordering': ['topic'],
            },
        ),
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='internal_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated_at')),
                ('is_actual', models.BooleanField(default=False, verbose_name='is_actual')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('main_text', models.TextField(blank=True, null=True, verbose_name='Основной текст')),
                ('course_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='topic_subtopic', to='educational_module.coursetopic', verbose_name='тема курса')),
            ],
            options={
                'verbose_name': 'Под-тема',
                'verbose_name_plural': 'Под-темы',
                'ordering': ['course_topic', 'id'],
            },
        ),
        migrations.AddField(
            model_name='coursetopic',
            name='training_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='course_topics', to='educational_module.trainingcourse', verbose_name='курс самоподготовки'),
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='internal_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated_at')),
                ('is_actual', models.BooleanField(default=False, verbose_name='is_actual')),
                ('number', models.CharField(blank=True, max_length=5, null=True, verbose_name='порядковый номер')),
                ('text', models.TextField(blank=True, null=True, verbose_name='текст')),
                ('is_correct', models.BooleanField(default=False, verbose_name='верно')),
                ('topic_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='answer_options', to='educational_module.topicquestion', verbose_name='вопрос по теме')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
                'ordering': ['id', 'number'],
            },
        ),
    ]
