# Generated by Django 4.2.3 on 2024-04-01 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='internal_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated_at')),
                ('is_actual', models.BooleanField(default=False, verbose_name='is_actual')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('main_text', models.TextField(blank=True, null=True, verbose_name='main_text')),
            ],
            options={
                'verbose_name': 'CourseTopic',
                'verbose_name_plural': 'CourseTopics',
                'ordering': ['training_course', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TrainingCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='internal_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated_at')),
                ('is_actual', models.BooleanField(default=False, verbose_name='is_actual')),
                ('title', models.CharField(blank=True, max_length=400, null=True, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('user', models.ManyToManyField(blank=True, null=True, to='bot.telegramuser')),
            ],
            options={
                'verbose_name': 'TrainingCourse',
                'verbose_name_plural': 'TrainingCourses',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TopicQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='internal_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated_at')),
                ('is_actual', models.BooleanField(default=False, verbose_name='is_actual')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='title')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='topic_questions', to='educational_module.coursetopic', verbose_name='topic')),
                ('training', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='educational_module.trainingcourse', verbose_name='course')),
            ],
            options={
                'verbose_name': 'TopicQuestion',
                'verbose_name_plural': 'TopicQuestions',
                'ordering': ['topic'],
            },
        ),
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='internal_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated_at')),
                ('is_actual', models.BooleanField(default=False, verbose_name='is_actual')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('main_text', models.TextField(blank=True, null=True, verbose_name='main_text')),
                ('course_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='topic_subtopic', to='educational_module.coursetopic', verbose_name='course_topic')),
            ],
            options={
                'verbose_name': 'Subtopic',
                'verbose_name_plural': 'Subtopics',
                'ordering': ['course_topic', 'id'],
            },
        ),
        migrations.AddField(
            model_name='coursetopic',
            name='training_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='course_topics', to='educational_module.trainingcourse', verbose_name='training_course'),
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='internal_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated_at')),
                ('is_actual', models.BooleanField(default=False, verbose_name='is_actual')),
                ('number', models.CharField(blank=True, max_length=5, null=True, verbose_name='number')),
                ('text', models.TextField(blank=True, null=True, verbose_name='text')),
                ('is_correct', models.BooleanField(default=False, verbose_name='is_correct')),
                ('topic_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='answer_options', to='educational_module.topicquestion', verbose_name='topic_question')),
            ],
            options={
                'verbose_name': 'AnswerOption',
                'verbose_name_plural': 'AnswerOptions',
                'ordering': ['id', 'number'],
            },
        ),
    ]
