# Generated by Django 4.2.3 on 2024-04-25 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_telegramgroup'),
        ('educational_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcourse',
            name='group',
            field=models.ManyToManyField(blank=True, null=True, to='bot.telegramgroup'),
        ),
    ]
