# Generated by Django 4.2.3 on 2024-05-29 12:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educational_module', '0006_coursetopic_min_test_percent_topic_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topicquestion',
            options={'ordering': ['training'], 'verbose_name': 'Вопрос по теме', 'verbose_name_plural': 'Вопросы по темам'},
        ),
        migrations.RemoveField(
            model_name='coursetopic',
            name='min_test_percent_topic',
        ),
        migrations.RemoveField(
            model_name='topicquestion',
            name='topic',
        ),
        migrations.AlterField(
            model_name='coursetopic',
            name='main_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Основной текст'),
        ),
    ]
