# Generated by Django 4.2.3 on 2024-06-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_module', '0008_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetopic',
            name='main_text_readuser',
            field=models.BooleanField(default=False, verbose_name='main text read user'),
        ),
        migrations.AddField(
            model_name='coursetopic',
            name='main_text_webapp_readuser',
            field=models.BooleanField(default=False, verbose_name='main text web app read user'),
        ),
        migrations.AddField(
            model_name='coursetopic',
            name='pdf_file_readuser',
            field=models.BooleanField(default=False, verbose_name='PDF file read user'),
        ),
    ]
