# Generated by Django 4.2.3 on 2024-09-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_module', '0015_company_version_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='image_progess_bad',
            field=models.ImageField(blank=True, null=True, upload_to='test failed', verbose_name='Негативное изображение для прогресса'),
        ),
        migrations.AddField(
            model_name='company',
            name='image_progess_good',
            field=models.ImageField(blank=True, null=True, upload_to='test passed', verbose_name='Позитивное изображение для прогресса'),
        ),
        migrations.AddField(
            model_name='company',
            name='image_spravka_for_bot',
            field=models.ImageField(blank=True, null=True, upload_to='start_images', verbose_name='Изображение для справки о боте'),
        ),
    ]
