# Generated by Django 4.2.3 on 2024-09-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_module', '0016_company_image_progess_bad_company_image_progess_good_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicquestion',
            name='is_multiple_choise',
            field=models.BooleanField(default=False),
        ),
    ]
