# Generated by Django 4.2.3 on 2024-09-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_module', '0017_topicquestion_is_multiple_choise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicquestion',
            name='is_multiple_choise',
        ),
        migrations.AddField(
            model_name='topicquestion',
            name='is_multiple_choiсe',
            field=models.BooleanField(default=False, verbose_name='Несколько ответов'),
        ),
    ]
