# Generated by Django 4.2.3 on 2024-09-17 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educational_module', '0018_remove_topicquestion_is_multiple_choise_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topicquestion',
            old_name='is_multiple_choiсe',
            new_name='is_multiple_choice',
        ),
    ]
