# Generated by Django 4.2.3 on 2024-09-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_telegramuser_first_name_telegramuser_last_name_and_more'),
        ('educational_module', '0019_rename_is_multiple_choiсe_topicquestion_is_multiple_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingcourse',
            name='group',
            field=models.ManyToManyField(blank=True, to='bot.telegramgroup', verbose_name='Группа пользователей'),
        ),
        migrations.AlterField(
            model_name='trainingcourse',
            name='user',
            field=models.ManyToManyField(blank=True, to='bot.telegramuser', verbose_name='Пользователь'),
        ),
    ]
