# Generated by Django 4.2.3 on 2024-09-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_module', '0022_trainingcourse_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcourse',
            name='archive',
            field=models.BooleanField(default=False, verbose_name='Архивный'),
        ),
        migrations.AlterField(
            model_name='answeroption',
            name='is_actual',
            field=models.BooleanField(default=False, verbose_name='Актуальный'),
        ),
        migrations.AlterField(
            model_name='coursetopic',
            name='is_actual',
            field=models.BooleanField(default=False, verbose_name='Актуальный'),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='is_actual',
            field=models.BooleanField(default=False, verbose_name='Актуальный'),
        ),
        migrations.AlterField(
            model_name='topicquestion',
            name='is_actual',
            field=models.BooleanField(default=False, verbose_name='Актуальный'),
        ),
        migrations.AlterField(
            model_name='trainingcourse',
            name='is_actual',
            field=models.BooleanField(default=False, verbose_name='Актуальный'),
        ),
    ]
