# Generated by Django 4.2.20 on 2025-08-20 07:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lightning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_draft', models.BooleanField(default=True, verbose_name='Черновик')),
                ('name', models.CharField(max_length=100, verbose_name='Молния')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата')),
                ('min_test_percent_course', models.PositiveSmallIntegerField(default=90, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Минимальный процент для прохождения теста')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Контент')),
                ('image', models.ImageField(blank=True, null=True, upload_to='lightning/images/', verbose_name='Изображение')),
                ('file', models.FileField(blank=True, null=True, upload_to='lightning/files/', verbose_name='Файл')),
                ('department', models.ManyToManyField(blank=True, to='organization.department', verbose_name='Подразделения')),
                ('group', models.ManyToManyField(blank=True, to='bot.telegramgroup', verbose_name='Группа пользователей')),
                ('job_titles', models.ManyToManyField(blank=True, to='organization.jobtitle', verbose_name='Должности')),
                ('user', models.ManyToManyField(blank=True, to='bot.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Молния',
                'verbose_name_plural': 'Молнии',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LightningSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Настройка оповещений', max_length=200, verbose_name='Наименование настройки')),
                ('gif', models.FileField(blank=True, null=True, upload_to='gif_lightning/', verbose_name='Общий GIF для молний')),
                ('enable_scheduler', models.BooleanField(default=True, verbose_name='Включить планировщик повторных оповещений')),
                ('schedule_start_hour', models.PositiveSmallIntegerField(default=10, help_text='Час в 24-часовом формате для запуска задачи отправки (0-23)', verbose_name='Час запуска')),
                ('schedule_interval_hours', models.FloatField(default=24.0, help_text='Как часто запускать задачу отправки (в часах)', verbose_name='Интервал повтора (часы)')),
                ('monday', models.BooleanField(default=True, verbose_name='Понедельник')),
                ('tuesday', models.BooleanField(default=True, verbose_name='Вторник')),
                ('wednesday', models.BooleanField(default=True, verbose_name='Среда')),
                ('thursday', models.BooleanField(default=True, verbose_name='Четверг')),
                ('friday', models.BooleanField(default=True, verbose_name='Пятница')),
                ('saturday', models.BooleanField(default=True, verbose_name='Суббота')),
                ('sunday', models.BooleanField(default=True, verbose_name='Воскресенье')),
                ('batch_size', models.PositiveSmallIntegerField(default=25, help_text='Количество сообщений в одном пакете', verbose_name='Размер пакета')),
                ('delay_between_users', models.FloatField(default=0.15, help_text='Пауза между отправкой сообщений разным пользователям в одном пакете', verbose_name='Задержка между пользователями (сек)')),
                ('delay_between_batches', models.PositiveSmallIntegerField(default=3, help_text='Пауза между обработкой разных пакетов', verbose_name='Задержка между пакетами (сек)')),
                ('max_retry_attempts', models.PositiveSmallIntegerField(default=5, help_text='Максимальное количество попыток отправки сообщения', verbose_name='Макс. число попыток')),
                ('cleanup_age_days', models.PositiveSmallIntegerField(default=30, help_text='Максимальное количество дней по хранению старых записей', verbose_name='Дни до очистки')),
            ],
            options={
                'verbose_name': 'Настройки Молнии',
                'verbose_name_plural': 'Настройки молний',
            },
        ),
        migrations.CreateModel(
            name='LightningQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Вопрос')),
                ('is_multiple_choice', models.BooleanField(default=False, verbose_name='Несколько ответов')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Порядок')),
                ('lightning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='lightning.lightning', verbose_name='Молния')),
            ],
            options={
                'verbose_name': 'Вопрос молнии',
                'verbose_name_plural': 'Вопросы молнии',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LightningAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст ответа')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный ответ')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Порядок')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='lightning.lightningquestion', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вариант ответа молнии',
                'verbose_name_plural': 'Варианты ответов молнии',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserTestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lightning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lightning.lightning', verbose_name='Молния')),
                ('telegramuser', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bot.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Количество попыток',
                'verbose_name_plural': 'Количество попыток',
                'unique_together': {('telegramuser', 'lightning')},
            },
        ),
        migrations.CreateModel(
            name='LightningTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата записи теста')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновление записи теста')),
                ('complete', models.BooleanField(default=False, verbose_name='Успешно')),
                ('quantity_correct', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Процент правильных ответов')),
                ('quantity_not_correct', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Процент не правильных ответов')),
                ('lightning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lightning.lightning', verbose_name='Молния')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Результат тестирования',
                'verbose_name_plural': 'Результаты тестирования',
                'ordering': ['created_at'],
                'unique_together': {('user', 'lightning')},
            },
        ),
        migrations.CreateModel(
            name='LightningRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Прочитано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_read', models.BooleanField(default=False)),
                ('lightning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lightning.lightning', verbose_name='Молния')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Статус чтения молнии',
                'verbose_name_plural': 'Статусы чтения молний',
                'ordering': ['created_at'],
                'unique_together': {('user', 'lightning')},
            },
        ),
    ]
