# Generated by Django 4.2.20 on 2025-09-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightningsetting',
            name='enable_gif',
            field=models.BooleanField(default=False, help_text='Если включено и загружен GIF, отправлять анимацию перед текстом', verbose_name='Отправлять GIF перед сообщением'),
        ),
        migrations.AddField(
            model_name='lightningsetting',
            name='poll_interval_minutes',
            field=models.PositiveSmallIntegerField(default=5, help_text='Как часто поллер проверяет, пора ли запускать рассылку', verbose_name='Период опроса планировщика (мин)'),
        ),
    ]
