# Generated by Django 4.2.9 on 2024-01-26 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DirectoryServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_services', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_eriell', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('username_telegram', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_text', models.TextField()),
                ('application_from', models.DateTimeField()),
                ('answer', models.TextField()),
                ('time_answer', models.DateTimeField()),
                ('status', models.CharField(max_length=100)),
                ('name_services', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='telegram_bot.directoryservices')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField(max_length=50)),
                ('block', models.CharField(max_length=50)),
                ('office_workplace', models.CharField(max_length=100)),
                ('internal_number', models.IntegerField(max_length=50)),
                ('mobile_phone', models.IntegerField(max_length=50)),
                ('application_text', models.TextField()),
                ('name_services', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='telegram_bot.directoryservices')),
            ],
        ),
    ]
