# Generated by Django 4.2.9 on 2024-02-01 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='user_eriell',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='telegram_bot.user'),
        ),
    ]
