# Generated by Django 4.2.9 on 2024-02-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0003_alter_user_email_alter_user_user_eriell_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='applications',
            name='application_from',
        ),
        migrations.RemoveField(
            model_name='applications',
            name='name_services',
        ),
        migrations.RemoveField(
            model_name='applications',
            name='status',
        ),
        migrations.RemoveField(
            model_name='applications',
            name='time_answer',
        ),
        migrations.RemoveField(
            model_name='applications',
            name='user_eriell',
        ),
        migrations.AddField(
            model_name='applications',
            name='block',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applications',
            name='floor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applications',
            name='internal_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applications',
            name='mobile_phone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applications',
            name='office_workplace',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applications',
            name='service_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='applications',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='applications',
            name='application_text',
            field=models.TextField(null=True),
        ),
    ]
