# Generated by Django 4.2.9 on 2024-02-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0004_remove_applications_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='user_id',
        ),
        migrations.AddField(
            model_name='applications',
            name='user_eriell',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
