# Generated by Django 4.2.9 on 2024-02-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0005_remove_applications_user_id_applications_user_eriell'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='service_id',
        ),
        migrations.AddField(
            model_name='applications',
            name='service_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
