# Generated by Django 4.2.9 on 2024-02-05 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0006_remove_applications_service_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directoryservices',
            old_name='name_services',
            new_name='service_name',
        ),
    ]
