# Generated by Django 4.2.9 on 2024-02-05 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0007_rename_name_services_directoryservices_service_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='service_name',
        ),
        migrations.RemoveField(
            model_name='directoryservices',
            name='service_name',
        ),
        migrations.AddField(
            model_name='applications',
            name='name_services',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='telegram_bot.directoryservices'),
        ),
        migrations.AddField(
            model_name='directoryservices',
            name='name_services',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='name_services',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='telegram_bot.directoryservices'),
        ),
    ]
