# Generated by Django 4.2.9 on 2024-02-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0008_remove_applications_service_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='name_services',
        ),
        migrations.AddField(
            model_name='applications',
            name='service_id',
            field=models.IntegerField(null=True),
        ),
    ]
