# Generated by Django 4.2.9 on 2024-02-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0009_remove_applications_name_services_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='service_id',
        ),
        migrations.AddField(
            model_name='applications',
            name='name_services',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
