# Generated by Django 4.2.9 on 2024-02-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0010_remove_applications_service_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_eriell', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('username_telegram', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('internal_number', models.CharField(max_length=100, null=True)),
                ('mobile_phone', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='applications',
            name='building',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
