# Generated by Django 4.2.3 on 2024-08-09 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educational_module', '0013_alter_company_spravka_for_bot'),
        ('users', '0002_customuser_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='educational_module.company', verbose_name='Компания'),
        ),
    ]
