# Generated by Django 5.2.14 on 2026-05-24 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geozone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('omnicomm_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='ID Omnicomm')),
                ('omnicomm_uuid', models.UUIDField(blank=True, null=True, unique=True, verbose_name='UUID Omnicomm')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('is_used_in_matrix', models.BooleanField(default=True, verbose_name='Используется в матрице')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Геозона',
                'verbose_name_plural': 'Геозоны',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True, verbose_name='Госномер')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Наименование')),
                ('omnicomm_uuid', models.UUIDField(blank=True, null=True, unique=True, verbose_name='UUID Omnicomm')),
                ('omnicomm_vehicle_id', models.BigIntegerField(blank=True, help_text='Числовой идентификатор ТС во внешней системе для отчётных запросов; при реальной интеграции требует подтверждения.', null=True, unique=True, verbose_name='ID ТС Omnicomm')),
                ('terminal_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='ID терминала')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('is_subject_to_inspection', models.BooleanField(default=True, verbose_name='Участвует в проверках')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Транспортное средство',
                'verbose_name_plural': 'Транспортные средства',
                'ordering': ('plate_number',),
            },
        ),
        migrations.CreateModel(
            name='VehicleMorningGeozone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('status', models.CharField(choices=[('detected', 'Геозона определена'), ('outside', 'Вне геозон'), ('no_data', 'Нет данных')], default='no_data', max_length=20, verbose_name='Статус')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='Время нахождения, сек.')),
                ('entered_at', models.DateTimeField(blank=True, null=True, verbose_name='Время входа')),
                ('exited_at', models.DateTimeField(blank=True, null=True, verbose_name='Время выхода')),
                ('source', models.CharField(default='omnicomm', max_length=30, verbose_name='Источник')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('geozone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_morning_locations', to='fleet.geozone', verbose_name='Геозона')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='morning_geozones', to='fleet.vehicle', verbose_name='ТС')),
            ],
            options={
                'verbose_name': 'Утренняя геозона ТС',
                'verbose_name_plural': 'Утренние геозоны ТС',
                'ordering': ('-date', 'vehicle__plate_number'),
                'constraints': [models.UniqueConstraint(fields=('vehicle', 'date'), name='fleet_vehiclemorninggeozone_vehicle_date_unique')],
            },
        ),
    ]
