# Generated by Django 5.2.14 on 2026-05-24 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField(verbose_name='Дата проверки')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Удалено')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_inspections', to=settings.AUTH_USER_MODEL, verbose_name='Создал запись')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='fleet.vehicle', verbose_name='ТС')),
            ],
            options={
                'verbose_name': 'Проверка ТС',
                'verbose_name_plural': 'Проверки ТС',
                'ordering': ('-inspection_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='InspectionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('file_url', models.URLField(verbose_name='Ссылка на файл')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='MIME-тип')),
                ('size_bytes', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Размер, байт')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружено')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='inspections.inspection', verbose_name='Проверка')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_inspection_files', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Файл проверки',
                'verbose_name_plural': 'Файлы проверок',
                'ordering': ('-uploaded_at', 'file_name'),
            },
        ),
    ]
