upstream api {
    server backend:8080;
}

upstream front {
    server frontend:3000;
}

server {
    listen 80;
    listen [::]:80;
    server_name learning.engsdrilling.ru;

    client_max_body_size 4G;
    keepalive_timeout 50;

    
    location ~ ^/(api|admin|webapp)/ {
        proxy_pass http://api;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
    }
    
    location / {
        proxy_pass http://front;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
    }

    location = /favicon.ico {
        access_log off;
        log_not_found off;
    }

    location /assets/ {
        autoindex on;
        alias /var/app/assets/;
    }

    location /media/ {
        autoindex on;
        alias /var/app/media/;
    }

    location /static/ {
        autoindex on;
        alias /var/app/staticfiles/;
    }

}
