version: '3.8'

services:
  web:
    build: .
    command: gunicorn --workers=3 --bind 0.0.0.0:8000 botserv.wsgi:application
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"

  bot:
    build: .
    command: python manage.py bot
    volumes:
      - .:/app

volumes:
  static_volume:
