# Generated by Django 5.2.14 on 2026-05-24 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('omnicomm', 'Omnicomm'), ('retailiqa', 'Retailiqa')], max_length=20, verbose_name='Провайдер')),
                ('sync_type', models.CharField(max_length=100, verbose_name='Тип синхронизации')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('running', 'Выполняется'), ('success', 'Успешно'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начато')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
                ('records_received', models.PositiveIntegerField(default=0, verbose_name='Получено записей')),
                ('records_created', models.PositiveIntegerField(default=0, verbose_name='Создано записей')),
                ('records_updated', models.PositiveIntegerField(default=0, verbose_name='Обновлено записей')),
                ('error_message', models.TextField(blank=True, verbose_name='Описание ошибки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Запуск синхронизации',
                'verbose_name_plural': 'Запуски синхронизации',
                'ordering': ('-created_at',),
            },
        ),
    ]
