# Generated by Django 4.2.20 on 2025-06-20 08:53

import app.bot.models.education_data
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='TelegramGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('is_actual', models.BooleanField(default=True, verbose_name='Is actual')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование группы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Группа студентов',
                'verbose_name_plural': 'Группы студентов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('is_actual', models.BooleanField(default=True, verbose_name='Is actual')),
                ('state', models.IntegerField(choices=[(0, 'Not active'), (1, 'Active'), (2, 'Deleted')], default=0, null=True, verbose_name='State')),
                ('user_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('user_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Username')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='ФИО')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('date_of_birth', models.CharField(blank=True, max_length=10, null=True, verbose_name='Дата рождения')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email')),
                ('language', models.CharField(blank=True, default='ru', max_length=20, null=True, verbose_name='Язык')),
                ('image', models.ImageField(blank=True, null=True, upload_to='telegramuser', verbose_name='Фото пользователя')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UserRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('is_actual', models.BooleanField(default=True, verbose_name='Is actual')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('read_at', models.DateTimeField(auto_now=True, verbose_name='Дата прочтения')),
            ],
            options={
                'verbose_name': 'Прочтение материала',
                'verbose_name_plural': 'Прочтения материалов',
            },
        ),
        migrations.CreateModel(
            name='UserTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('is_actual', models.BooleanField(default=True, verbose_name='Is actual')),
                ('user_answer', models.JSONField(default=app.bot.models.education_data.default_user_answer, verbose_name='Ответы пользователя')),
                ('complete', models.BooleanField(default=False, verbose_name='Успешно пройден')),
                ('quantity_correct', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Процент правильных ответов')),
                ('quantity_not_correct', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Процент неправильных ответов')),
            ],
            options={
                'verbose_name': 'Тест пользователя',
                'verbose_name_plural': 'Тесты пользователей',
            },
        ),
    ]
