# Generated by Django 4.2.20 on 2025-06-20 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning_app', '0001_initial'),
        ('organization', '0001_initial'),
        ('bot', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertest',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning_app.topicquestion', verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='usertest',
            name='training',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning_app.trainingcourse', verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='usertest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.telegramuser', verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='userread',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_app.trainingcourse', verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='userread',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_app.coursetopic', verbose_name='Тема курса'),
        ),
        migrations.AddField(
            model_name='userread',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.telegramuser', verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.department', verbose_name='Подразделение'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='job_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.jobtitle', verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='telegramgroup',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='groups', to='bot.telegramuser', verbose_name='Пользователи'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telegram_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_user', to='bot.telegramuser', verbose_name='Telegram пользователь'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterUniqueTogether(
            name='userread',
            unique_together={('user', 'course', 'topic')},
        ),
    ]
