# Generated by Django 4.2.20 on 2025-07-25 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_add_password_reset_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramgroup',
            name='is_actual',
            field=models.BooleanField(default=True, verbose_name='Актуальное'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='is_actual',
            field=models.BooleanField(default=True, verbose_name='Актуальное'),
        ),
        migrations.AlterField(
            model_name='userread',
            name='is_actual',
            field=models.BooleanField(default=True, verbose_name='Актуальное'),
        ),
        migrations.AlterField(
            model_name='usertest',
            name='is_actual',
            field=models.BooleanField(default=True, verbose_name='Актуальное'),
        ),
    ]
