# Generated by Django 4.2.20 on 2025-07-30 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_telegramgroup_is_actual_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertest',
            name='question',
        ),
    ]
