# Generated by Django 4.2.20 on 2025-10-31 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_remove_usertest_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('is_actual', models.BooleanField(default=True, verbose_name='Актуальное')),
                ('points', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Количество баллов')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='bot.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Рейтинг пользователя',
                'verbose_name_plural': 'Рейтинг пользователей',
                'ordering': ['-points', 'user_id'],
            },
        ),
    ]
