# Generated by Django 4.2.20 on 2025-11-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_userrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='personal_data_consent',
            field=models.BooleanField(default=False, verbose_name='Согласие на обработку персональных данных'),
        ),
    ]
