# Generated by Django 4.2.20 on 2025-12-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_telegramuser_personal_data_consent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='state',
            field=models.IntegerField(choices=[(0, 'Неактивный'), (1, 'Активный'), (2, 'Удалённый')], default=0, null=True, verbose_name='Статус'),
        ),
    ]
