# Generated by Django 4.2.20 on 2025-12-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_alter_telegramuser_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramuser',
            old_name='user_id',
            new_name='telegram_id',
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='guid_1c',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Код 1С'),
        ),
    ]
