# Generated by Django 4.2.20 on 2025-12-25 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_rename_user_id_telegramuser_telegram_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='state',
            field=models.IntegerField(choices=[(0, 'Неактивный'), (1, 'Активный'), (2, 'Удалённый'), (3, 'Нужно подтвердить')], default=0, null=True, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='SubscriptionUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('is_actual', models.BooleanField(default=True, verbose_name='Актуальное')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подписка пользователя',
                'verbose_name_plural': 'Подписки пользователей',
                'ordering': ['user'],
            },
        ),
    ]
