# Generated by Django 4.2.20 on 2026-01-20 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0010_topicquestion_course_topic'),
        ('bot', '0010_alter_telegramuser_state_subscriptionuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertest',
            name='course_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning_app.coursetopic', verbose_name='Тема курса'),
        ),
    ]
